### ISSUE TITLE
[Issue]: Release Date Not Printed On New Versions

### ISSUE THREAD

**Issue by TJruee** [MichaelYochpaz/iSubRip#65] opened 2024-03-16 16:23 UTC
### Question

like this?
It gives more information to some 'links in one copy'
It was in the previous versions

Found movie: Bob Marley: One Love (2024)
Release date (iTunes): 2024-03-19.

**Comment by MichaelYochpaz** [comment] 2024-03-16 16:31
Hey, sorry, but I don't understand what you're trying to say.
What's the question here?
What versions are you referring to?

**Comment by TJruee** [comment] 2024-03-16 16:34
In version 2.5.2 - no release date appears

in versions 2.4.3 ומטה its appears
@MichaelYochpaz

**Comment by MichaelYochpaz** [comment] 2024-03-16 16:44
Seems like you're right, was able to reproduce this. I'll work on a fix.
Next time, though, please open this as an Issue / Bug report with all the relevant information, and not a question (since this is obviously a bug report and not a question).

**Comment by TJruee** [comment] 2024-03-18 18:47
Thanks.

**Comment by MichaelYochpaz** [comment] 2024-04-09 20:12
Issue was fixed on the new [v2.5.3 update](https://github.com/MichaelYochpaz/iSubRip/releases/tag/v2.5.3).

**Closed by MichaelYochpaz** 2024-04-09 20:12 UTC
Labels: bug
