### ISSUE TITLE
[Question]: It showed me error, how to fix it?

### ISSUE THREAD

**Issue by meir4503** [MichaelYochpaz/iSubRip#49] opened 2023-07-07 19:13 UTC
### Question

Thats the error i got:
isubrip : The term 'isubrip' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ isubrip https://tv.apple.com/il/movie/shazam-fury-of-the-gods/umc.cmc.tu1nk49297soejvl43t2ro76
+ ~~~~~~~
    + CategoryInfo          : ObjectNotFound: (isubrip:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by MichaelYochpaz** [comment] 2023-07-08 09:22
Hey, how did you install it? What Python version do you have (run `python --version`)?
If you run `pip freeze`, does `isubrip` appear there on the list?

Also, note that after installing (that's true to any CLI tool by the way), you'll need to reopen the terminal (in this case, PowerShell) window, in order for it to detect newly installed software.

**Comment by meir4503** [comment] 2023-07-08 11:07
> Hey, how did you install it? What Python version do you have (run `python --version`)? If you run `pip freeze`, does `isubrip` appear there on the list?
> 
> Also, note that after installing (that's true to any CLI tool by the way), you'll need to reopen the terminal (in this case, PowerShell) window, in order for it to detect newly installed software.

Hey, thanks for your reply.
my phyton version is the latest (3.11.4) and when i run pip freeze nothing happend.
I follow your instructions and run all the comands.

**Comment by MichaelYochpaz** [comment] 2023-07-08 17:27
What do you mean by "nothing happens"? You get no output at all (a blank line)? You get the same error that the command could not be found?

What happened when you ran`pip install isubrip`? You got output saying it was successfully installed?

Try running `python -m pip install isubrip`.

**Comment by meir4503** [comment] 2023-07-08 18:59
היי, רק עכשיו ראיתי שאתה ישראלי.
הפקודה pip install isubrip עבדה ועכשיו הוא מוריד לי את הכתוביות.
איך אני משנה שזה יוריד לי רק את הכתוביות בעברית ולא את כל הכתוביות?

**Comment by meir4503** [comment] 2023-07-08 18:59
> What do you mean by "nothing happens"? You get no output at all (a blank line)? You get the same error that the command could not be found?
> 
> What happened when you ran `pip install isubrip`? You got output saying it was successfully installed?
> 
> Try running `python -m pip install isubrip`.

היי, רק עכשיו ראיתי שאתה ישראלי.
הפקודה pip install isubrip עבדה ועכשיו הוא מוריד לי את הכתוביות.
איך אני משנה שזה יוריד לי רק את הכתוביות בעברית ולא את כל הכתוביות?

**Comment by meir4503** [comment] 2023-07-08 19:02
> What do you mean by "nothing happens"? You get no output at all (a blank line)? You get the same error that the command could not be found?
> 
> What happened when you ran `pip install isubrip`? You got output saying it was successfully installed?
> 
> Try running `python -m pip install isubrip`.

The comand pip install isubrip worked great and now it download me the subtitles so thanks you very much!
How i can make it download only he subtitles and not all the available subtitles?

**Comment by MichaelYochpaz** [comment] 2023-07-08 19:33
Great.
See https://github.com/MichaelYochpaz/iSubRip#configuration and https://github.com/MichaelYochpaz/iSubRip/blob/main/config.toml for configuration.

Closing this as the issue is resolved.

**Closed by MichaelYochpaz** 2023-07-08 19:33 UTC
Labels: question
