### ISSUE TITLE
Doesn't scrape if movie has '?' in the title

### ISSUE THREAD

**Issue by mataski** [MichaelYochpaz/iSubRip#14] opened 2022-05-29 19:57 UTC
Movie "Can You Hear Us Now?" has ? in the title, and ? is not supported in Windows for folders/filenames.

```
isubrip https://itunes.apple.com/us/movie/can-you-hear-us-now/id1617191490
Scraping https://itunes.apple.com/us/movie/can-you-hear-us-now/id1617191490...
Found movie: Can You Hear Us Now?
Traceback (most recent call last):
  File "%appdata%\local\programs\python\python38-32\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "%appdata%\local\programs\python\python38-32\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "%appdata%\local\programs\python\python38-32\scripts\isubrip.exe\__main__.py", line 7, in <module>
  File "%appdata%\local\programs\python\python38-32\lib\site-packages\isubrip\__main__.py", line 91, in main
    os.makedirs(current_download_path, exist_ok=True)
  File "%appdata%\local\programs\python\python38-32\lib\os.py", line 221, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'C:\\%appdata%\\Local\\Temp\\iSubRip\\Can.You.Hear.Us.Now?.iT.WEB'
```

Also some other error:

```
isubrip https://itunes.apple.com/us/movie/climate-crisis-flooding/id1615085644
Scraping https://itunes.apple.com/us/movie/climate-crisis-flooding/id1615085644...
Found movie: Climate Crisis: Flooding
Error: No valid playlist could be found.

--------------------------------------------------

```

**Comment by MichaelYochpaz** [comment] 2022-05-30 18:12
Hey, thanks for reporting the bug :)
I pushed a fix (commit 121f9735f6d76e694737f21b95ac87b4dc551cd0) to fix the issue, it will be included in the next release.  
If you can't wait you can [install the package from source](https://github.com/MichaelYochpaz/iSubRip#git-source-code).

Regarding the second "error", that's not a bug, there aren't any subtitles for this iTunes movie (at least for this specific id).
The "CC" subtitles mentioned on the page are part of the video stream and aren't a separate stream, so it's not obtainable by iSubRip.
The first movie also has no subtitles.

**Closed by MichaelYochpaz** 2022-05-30 18:12 UTC
Labels: bug
