### ISSUE TITLE
[Issue]: I have to sometimes try 2-3 times to rip subtitles

### ISSUE THREAD

**Issue by insurw** [MichaelYochpaz/iSubRip#74] opened 2024-07-16 19:13 UTC
### Confirmations

- [X] I have checked the issues tab, and couldn't find an existing open issue for the issue I want to report.

### OS Type

Windows

### Python Version

Python 3.12.4

### Package Version

2.5.6

### Description

Now and then some rips get various error. Trying to rip right away a second or third time works. 
I think it started with version 2.5.4.
Looking back at output logs from February and June I can't find any similar errors, neither do I remember it being an issue.

[isubrip_2024-07-16_00-17-47-ERROR1.log](https://github.com/user-attachments/files/16255448/isubrip_2024-07-16_00-17-47-ERROR1.log)
[isubrip_2024-07-16_20-45-33-ERROR2.log](https://github.com/user-attachments/files/16255451/isubrip_2024-07-16_20-45-33-ERROR2.log)

### Output Log

```Text
<ERROR 1>
Error while scraping 'https://tv.apple.com/se/movie/insidious-the-last-key/umc.cmc.4gosbjb9erx6np1zvn684pfv5?playableId=tvs.sbd.9001%3A1319448763': [WinError 10051] A socket operation was attempted to an unreachable network

<ERROR 2 - Second rip attempt error output log is correct. It has "empty" error info.>
Error while scraping 'https://tv.apple.com/se/movie/knox-goes-away/umc.cmc.18b7pkpx0uhxdnqn3ey64y09i': [Errno 11004] getaddrinfo failed
Error while scraping 'https://tv.apple.com/se/movie/knox-goes-away/umc.cmc.18b7pkpx0uhxdnqn3ey64y09i':
```

### Config

```TOML
[downloads]
# Folder to downloads files to.
# The default "." value means it will download to the same folder the script ran from.
# Use double backslashes in path to avoid escaping characters. Example: "C:\\Users\\<username>\\Downloads\\"
folder = "."

# A list of iTunes language codes to download.
# An empty array (like the one currently being used) will result in downloading all of the available subtitles.
# Example: ["en-US", "fr-FR", "he"]
languages = ["en", "en-US", "en-UK", "sv", "sv-SE", "da", "da-DK", "no", "no-NO", "fi", "fi-FI"]
#languages = []

# Save files into a zip archive if there is more than one matching subtitles.
# Value can be either 'true' or 'false'.
zip = true

# Whether to convert subtitles to SRT format.
# NOTE: This can cause loss of subtitles metadata that is not supported by SRT format.
convert-to-srt = false
```

**Comment by MichaelYochpaz** [comment] 2024-07-27 18:53
Hey @insurw, looking at both of the attached log files, it seems that in both cases iSubRip worked as expected without any errors?
Did you perhaps attach the wrong log files?

Also, while I'll try my best to help, do note that network issues such as this, that are reported by single users and aren't wide-spread, usually indicate that the issue is specifically with your network / computer (firewall, network randomly disconnects, very slow connection, DNS resolving issues, etc.), like https://github.com/MichaelYochpaz/iSubRip/issues/71 for example.

**Comment by MichaelYochpaz** [comment] 2024-09-04 18:49
Closing this issue as there has been no response for over a month.
Feel free to reopen / add a comment if it's still relevant. @insurw

**Closed by MichaelYochpaz** 2024-09-04 18:49 UTC
Labels: bug
