### ISSUE TITLE
Can't configure isubrip on Mac OS?

### ISSUE THREAD

**Issue by kkycble** [MichaelYochpaz/iSubRip#22] opened 2022-07-20 04:41 UTC
I created the folder and the TOML file specified in README but it's not doing anything? I also do not find the default_config.toml in the folder either.

**Comment by MichaelYochpaz** [comment] 2022-07-20 20:29
I believe the issue is that the path is case-sensitive and is named after the package, so the folder should be named `iSubRip` instead of `isubrip` like the README says.

Could you please check that and let me know if it works? If it does I'll update the README.
The path should be `~/Library/Application Support/iSubRip/config.toml`

Regarding the `default_config.toml` file, it's not relevant here. It's installed alongside the code files when the package is installed and should not be altered.

**Comment by MichaelYochpaz** [comment] 2022-08-06 19:24
Fixed in the latest release (2.3.2)

**Closed by MichaelYochpaz** 2022-08-06 19:24 UTC
Labels: bug

**Comment by kkycble** [comment] 2022-08-07 09:19
> Fixed in the latest release (2.3.2)

It worked! Thanks for the effort and thank you for this project!
